#!/bin/bash

filename="$HOME/.work"

function usage() {
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  activity - register activity on a project"
  echo "  project - create a new project"
  echo "  list - list all projects"
  echo "  today - show all activity for today"
  echo "  yesterday - show all activity for yesterday"
  echo "  summary - show a summary of all projects"
  echo "  edit - edit the work file"
  echo "  help - show this help"
}

day=$(date "+%Y-%m-%d")

case $1 in
  activity)
    project=$("$0" list | fzf)
    if [ -z "$project" ]; then
      echo "No project selected"
      exit 1
    fi

    read -r -p "Activity: " activity
    echo "$day	activity	$project	$activity" >> "$filename"
    ;;
  project)
    read -r -p "Project name: " project_name
    echo "$day	project	$project_name" >> "$filename"
    ;;
  list)
    awk -F '\t' '/\tproject\t/{print $3}' "$filename" | sort | uniq
    ;;
  today)
    awk -F '\t' '$1 == "'"$day"'"' "$filename"
    ;;
  yesterday)
    today=$(date -d "$day" +%s)
    yesterday=$(date -d "@$((today - 86400))" "+%Y-%m-%d")
    awk -F '\t' '$1 == "'"$yesterday"'"' "$filename"
    ;;
  summary)
    (
    echo "Project	Last Updated"
    "$0" list | while read -r project; do
      last_updated=$(awk -F '\t' '/activity	'"$project"'	/{print $1}' "$filename" | sort | tail -n 1)
      echo "$project	$last_updated"
    done
    ) | column -t -s $'\t'
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  "")
    "$0" activity
    ;;
  *)
    echo "Unknown command: $1"
    usage
    exit 1
esac
